Feature: build entity_to_table_mapping.yml from schema files

  Rule: 每個 table 以 table name 作為 Entity mapping
    Example: single DBML file with two tables
      Given a temporary data directory
      And a schema file "schema.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        Table orders {
          id int [pk]
        }
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - users: users
          - orders: orders
        """

  Rule: 缺少 data 資料夾時要 stderr 失敗
    Example: data directory does not exist
      When build_mapping CLI is run against a missing data directory
      Then CLI exit code is 2
      And CLI stderr should contain "DATA_DIR not found"

  Rule: 缺少參數與環境變數時顯示 usage
    Example: no DATA_DIR argument and no env var
      When build_mapping CLI is run with no arguments
      Then CLI exit code is 1
      And CLI stderr should contain "usage: build_mapping.py"

  Rule: 跨檔重複 table 應被拒絕
    Example: same table name in two schema files
      Given a temporary data directory
      And a schema file "a.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        """
      And a schema file "b.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 3
      And CLI stderr should contain "duplicate table 'users'"

  Rule: 空資料目錄產出空 mapping 而非錯誤
    Example: data directory exists but contains no schema files
      Given a temporary data directory
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping: []
        """

  Rule: 相同內容第二次執行印 unchanged 不重寫檔案
    Example: running twice with unchanged schema
      Given a temporary data directory
      And a schema file "schema.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        """
      When build_mapping CLI is run against the data directory
      And build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And CLI stdout should contain "unchanged"

  Rule: DATA_DIR 可由環境變數提供
    Example: DATA_DIR env var set, no CLI argument
      Given a temporary data directory
      And a schema file "schema.dbml" with content:
        """
        Table products {
          id int [pk]
        }
        """
      When build_mapping CLI is run with DATA_DIR env var pointing to the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - products: products
        """

  Rule: 含 0 個 table 的合法 schema 檔不報錯
    Example: DBML file with no table definitions
      Given a temporary data directory
      And a schema file "empty.dbml" with content:
        """
        // no tables here
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping: []
        """
