Feature: build entity_to_table_mapping.yml from DBML

  Rule: DBML 的 Table 名被抽出為 plan 的待命名 worklist
    Example: single DBML file with two tables
      Given a temporary data directory
      And a schema file "schema.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        Table orders {
          id int [pk]
        }
        """
      When build_mapping plan is run against the data directory
      Then CLI exit code is 0
      And the plan for folder "." should list new tables ["users", "orders"]

  Rule: apply 依 naming 決議把 DBML table 落成 mapping
    Example: naming both tables writes the mapping in schema order
      Given a temporary data directory
      And a schema file "schema.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        Table orders {
          id int [pk]
        }
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {".": {"users": "Member", "orders": "PurchaseOrder"}}
        """
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - Member: users
          - PurchaseOrder: orders
        """

  Rule: DBML 跨檔重複 table 應被拒絕
    Example: same table name in two DBML files
      Given a temporary data directory
      And a schema file "a.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        """
      And a schema file "b.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        """
      When build_mapping plan is run against the data directory
      Then CLI exit code is 3
      And CLI stderr should contain "duplicate table 'users'"

  Rule: DBML 相同內容第二次 apply 印 unchanged 不重寫檔案
    Example: applying twice with unchanged DBML schema and naming
      Given a temporary data directory
      And a schema file "schema.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {".": {"users": "Member"}}
        """
      And build_mapping apply is run against the data directory with naming:
        """
        {}
        """
      Then CLI exit code is 0
      And CLI stdout should contain "unchanged"

  Rule: 含 0 個 table 的合法 DBML 檔不報錯
    Example: DBML file with no table definitions
      Given a temporary data directory
      And a schema file "empty.dbml" with content:
        """
        // no tables here
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {}
        """
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping: []
        """
