Feature: incremental spec-driven entity naming with global entity uniqueness

  Rule: plan 回報既有 entry 為已保留、未涵蓋的 table 為待命名
    Example: one table already mapped, one new
      Given a temporary data directory
      And a schema file "account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "room.pg.sql" with content:
        """
        CREATE TABLE public.rooms (
          id SERIAL PRIMARY KEY
        );
        """
      And an existing mapping "entity_to_table_mapping.yml" with content:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - Account: accounts
        """
      When build_mapping plan is run against the data directory
      Then CLI exit code is 0
      And the plan for folder "." should preserve existing {"accounts": "Account"}
      And the plan for folder "." should list new tables ["rooms"]

  Rule: apply 保留既有 entity name，只為新 table 落入指定命名
    Example: existing Account entry survives while the new table gets its spec name
      Given a temporary data directory
      And a schema file "account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "room.pg.sql" with content:
        """
        CREATE TABLE public.rooms (
          id SERIAL PRIMARY KEY
        );
        """
      And an existing mapping "entity_to_table_mapping.yml" with content:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - Account: accounts
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {".": {"rooms": "Room"}}
        """
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - Account: accounts
          - Room: rooms
        """

  Rule: 既有 mapping 為空時，apply 為每個 table 落入指定的非-identity 命名
    Example: two brand-new tables named from spec
      Given a temporary data directory
      And a schema file "account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "room.pg.sql" with content:
        """
        CREATE TABLE public.rooms (
          id SERIAL PRIMARY KEY
        );
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {".": {"accounts": "Account", "rooms": "ChatRoom"}}
        """
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - Account: accounts
          - ChatRoom: rooms
        """

  Rule: apply 缺少某個新 table 的命名時失敗
    Example: naming omits the rooms table
      Given a temporary data directory
      And a schema file "account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "room.pg.sql" with content:
        """
        CREATE TABLE public.rooms (
          id SERIAL PRIMARY KEY
        );
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {".": {"accounts": "Account"}}
        """
      Then CLI exit code is 5
      And CLI stderr should contain "missing naming"

  Rule: apply 產生跨資料夾撞名的 entity 時失敗並指名衝突
    Example: both folders name their table the same entity
      Given a temporary data directory
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "secondary/account.mysql.sql" with content:
        """
        CREATE TABLE `accounts` (
          `id` INT NOT NULL AUTO_INCREMENT,
          PRIMARY KEY (`id`)
        );
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {"primary": {"accounts": "Account"}, "secondary": {"accounts": "Account"}}
        """
      Then CLI exit code is 4
      And CLI stderr should contain "duplicate entity 'Account'"
