Feature: build entity_to_table_mapping.yml from MS SQL DDL

  Rule: MS SQL DDL 的 CREATE TABLE 以 table name 作為 Entity mapping
    Example: .mssql.sql file with bracket-quoted owner prefix and IDENTITY
      Given a temporary data directory
      And a schema file "schema.mssql.sql" with content:
        """
        CREATE TABLE [dbo].[customers] (
          [id] INT IDENTITY(1,1) NOT NULL,
          [name] NVARCHAR(100) NOT NULL,
          CONSTRAINT [PK_customers] PRIMARY KEY ([id])
        );
        CREATE TABLE [dbo].[invoices] (
          [id] INT IDENTITY(1,1) NOT NULL,
          [customer_id] INT NOT NULL,
          CONSTRAINT [PK_invoices] PRIMARY KEY ([id])
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - customers: customers
          - invoices: invoices
        """
