Feature: build entity_to_table_mapping.yml from MySQL DDL

  Rule: MySQL DDL 的 CREATE TABLE 以 table name 作為 Entity mapping
    Example: .mysql.sql file with backtick-quoted table and AUTO_INCREMENT
      Given a temporary data directory
      And a schema file "schema.mysql.sql" with content:
        """
        CREATE TABLE `users` (
          `id` INT NOT NULL AUTO_INCREMENT,
          `email` VARCHAR(255) NOT NULL,
          PRIMARY KEY (`id`)
        );
        CREATE TABLE `orders` (
          `id` INT NOT NULL AUTO_INCREMENT,
          `user_id` INT NOT NULL,
          PRIMARY KEY (`id`)
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - users: users
          - orders: orders
        """
