Feature: build entity_to_table_mapping.yml from MySQL DDL

  Rule: MySQL DDL 的 CREATE TABLE 名被抽出為 plan 的待命名 worklist
    Example: .mysql.sql file with backtick-quoted table and AUTO_INCREMENT
      Given a temporary data directory
      And a schema file "schema.mysql.sql" with content:
        """
        CREATE TABLE `users` (
          `id` INT NOT NULL AUTO_INCREMENT,
          `email` VARCHAR(255) NOT NULL,
          PRIMARY KEY (`id`)
        );
        CREATE TABLE `orders` (
          `id` INT NOT NULL AUTO_INCREMENT,
          `user_id` INT NOT NULL,
          PRIMARY KEY (`id`)
        );
        """
      When build_mapping plan is run against the data directory
      Then CLI exit code is 0
      And the plan for folder "." should list new tables ["users", "orders"]

  Rule: apply 依 naming 決議把 MySQL table 落成 mapping
    Example: naming both tables writes the mapping in schema order
      Given a temporary data directory
      And a schema file "schema.mysql.sql" with content:
        """
        CREATE TABLE `users` (
          `id` INT NOT NULL AUTO_INCREMENT,
          PRIMARY KEY (`id`)
        );
        CREATE TABLE `orders` (
          `id` INT NOT NULL AUTO_INCREMENT,
          PRIMARY KEY (`id`)
        );
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {".": {"users": "Member", "orders": "PurchaseOrder"}}
        """
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - Member: users
          - PurchaseOrder: orders
        """

  Rule: MySQL DDL 跨檔重複 table 應被拒絕
    Example: same table name in two MySQL DDL files
      Given a temporary data directory
      And a schema file "a.mysql.sql" with content:
        """
        CREATE TABLE `users` (
          `id` INT NOT NULL AUTO_INCREMENT,
          PRIMARY KEY (`id`)
        );
        """
      And a schema file "b.mysql.sql" with content:
        """
        CREATE TABLE `users` (
          `id` INT NOT NULL AUTO_INCREMENT,
          PRIMARY KEY (`id`)
        );
        """
      When build_mapping plan is run against the data directory
      Then CLI exit code is 3
      And CLI stderr should contain "duplicate table 'users'"

  Rule: 含 0 個 table 的合法 MySQL DDL 檔不報錯
    Example: MySQL DDL file with no table definitions
      Given a temporary data directory
      And a schema file "empty.mysql.sql" with content:
        """
        -- no tables here
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {}
        """
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping: []
        """
