Feature: build one entity_to_table_mapping.yml per schema-bearing folder

  # 一個資料夾只使用單一 schema 格式（全 SQL 或全 DBML），不把 DBML 與 SQL 混在同層。
  # DBML 的逐格式解析覆蓋見 dbml.feature；本檔聚焦「依資料夾分組產出」的機制，以 SQL DDL 表達。

  Rule: 同一資料夾的多個 DDL 檔合成同一份 mapping
    Example: primary folder with two PostgreSQL DDL files
      Given a temporary data directory
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "primary/room.pg.sql" with content:
        """
        CREATE TABLE public.rooms (
          id SERIAL PRIMARY KEY
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping at "primary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - accounts: accounts
          - rooms: rooms
        """

  Rule: 不同資料夾可使用不同 DDL 方言
    Example: primary uses PostgreSQL and secondary uses MySQL
      Given a temporary data directory
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "secondary/player.mysql.sql" with content:
        """
        CREATE TABLE `players` (
          `id` INT NOT NULL AUTO_INCREMENT,
          PRIMARY KEY (`id`)
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping at "primary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - accounts: accounts
        """
      And the generated mapping at "secondary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - players: players
        """

  Rule: 外層 DATA_DIR 直接含 schema 檔時外層自己也產出 mapping
    Example: root-level DDL file produces a root mapping alongside a subfolder mapping
      Given a temporary data directory
      And a schema file "game.pg.sql" with content:
        """
        CREATE TABLE public.games (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - games: games
        """
      And the generated mapping at "primary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - accounts: accounts
        """

  Rule: 根目錄沒有直屬 schema 檔時不產出根 mapping
    Example: only a subfolder carries schema files
      Given a temporary data directory
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping at "primary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - accounts: accounts
        """
      And no mapping file should be generated at the data directory root

  Rule: 不同資料夾的同名 table 可並存
    Example: same table name in primary and secondary folders is allowed
      Given a temporary data directory
      And a schema file "primary/users.pg.sql" with content:
        """
        CREATE TABLE public.users (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "secondary/users.mysql.sql" with content:
        """
        CREATE TABLE `users` (
          `id` INT NOT NULL AUTO_INCREMENT,
          PRIMARY KEY (`id`)
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping at "primary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - users: users
        """
      And the generated mapping at "secondary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - users: users
        """

  Rule: 同一資料夾內跨檔重複 table 仍被拒絕
    Example: duplicate table within a single subfolder
      Given a temporary data directory
      And a schema file "primary/a.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "primary/b.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 3
      And CLI stderr should contain "duplicate table 'accounts'"
