Feature: build entity_to_table_mapping.yml per subfolder from schema files

  Rule: 同一子資料夾的多個 schema 檔合併為一份 entity_to_table_mapping.yml
    Example: two .pg.sql files in primary/ merge into primary/entity_to_table_mapping.yml
      Given a temporary data directory
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "primary/room.pg.sql" with content:
        """
        CREATE TABLE public.rooms (
          id SERIAL PRIMARY KEY
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping at "primary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - accounts: accounts
          - rooms: rooms
        """

  Rule: 各子資料夾可各自使用不同 schema 檔類型並各產 entity_to_table_mapping.yml
    Example: primary/ uses .pg.sql and secondary/ uses .mysql.sql, each produces its own entity_to_table_mapping.yml
      Given a temporary data directory
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "secondary/player.mysql.sql" with content:
        """
        CREATE TABLE `players` (
          `id` INT NOT NULL AUTO_INCREMENT,
          PRIMARY KEY (`id`)
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping at "primary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - accounts: accounts
        """
      And the generated mapping at "secondary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - players: players
        """

  Rule: data 目錄根層有直接放的 schema 檔時，根層也產出 entity_to_table_mapping.yml
    Example: game.pg.sql at data root and account.pg.sql in primary/ produce two entity_to_table_mapping.yml files
      Given a temporary data directory
      And a schema file "game.pg.sql" with content:
        """
        CREATE TABLE public.games (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - games: games
        """
      And the generated mapping at "primary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - accounts: accounts
        """

  Rule: data 目錄根層沒有直接放的 schema 檔時，不產出根層 entity_to_table_mapping.yml
    Example: schema files only under primary/, no entity_to_table_mapping.yml at data root
      Given a temporary data directory
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping at "primary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - accounts: accounts
        """
      And no mapping file should be generated at the data directory root

  Rule: 不同子資料夾的同名 table 可各自納入，但兩者 entity name 不得全域撞名
    Example: users table in both primary/ and secondary/ with distinct entity names coexist
      Given a temporary data directory
      And a schema file "primary/users.pg.sql" with content:
        """
        CREATE TABLE public.users (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "secondary/users.mysql.sql" with content:
        """
        CREATE TABLE `users` (
          `id` INT NOT NULL AUTO_INCREMENT,
          PRIMARY KEY (`id`)
        );
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {"primary": {"users": "primary_users"}, "secondary": {"users": "secondary_users"}}
        """
      Then CLI exit code is 0
      And the generated mapping at "primary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - primary_users: users
        """
      And the generated mapping at "secondary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - secondary_users: users
        """

    Example: identity naming on same-named tables across folders collides and is rejected
      Given a temporary data directory
      And a schema file "primary/users.pg.sql" with content:
        """
        CREATE TABLE public.users (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "secondary/users.mysql.sql" with content:
        """
        CREATE TABLE `users` (
          `id` INT NOT NULL AUTO_INCREMENT,
          PRIMARY KEY (`id`)
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 4
      And CLI stderr should contain "duplicate entity 'users'"

  Rule: 同一子資料夾內多個 schema 檔重複定義同一 table 應被拒絕
    Example: duplicate accounts table across primary/a.pg.sql and primary/b.pg.sql fails with exit code 3
      Given a temporary data directory
      And a schema file "primary/a.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "primary/b.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 3
      And CLI stderr should contain "duplicate table 'accounts'"
