Feature: build entity_to_table_mapping.yml from PostgreSQL DDL

  Rule: PostgreSQL DDL 的 CREATE TABLE 名被抽出為 plan 的待命名 worklist
    Example: .pg.sql file with schema-qualified and IF NOT EXISTS table names
      Given a temporary data directory
      And a schema file "schema.pg.sql" with content:
        """
        CREATE TABLE IF NOT EXISTS public.accounts (
          id SERIAL PRIMARY KEY,
          email VARCHAR(255) NOT NULL
        );
        CREATE TABLE public.sessions (
          id SERIAL PRIMARY KEY,
          account_id INTEGER NOT NULL REFERENCES public.accounts(id)
        );
        """
      When build_mapping plan is run against the data directory
      Then CLI exit code is 0
      And the plan for folder "." should list new tables ["accounts", "sessions"]

  Rule: apply 依 naming 決議把 PostgreSQL table 落成 mapping
    Example: naming both tables writes the mapping in schema order
      Given a temporary data directory
      And a schema file "schema.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        CREATE TABLE public.sessions (
          id SERIAL PRIMARY KEY
        );
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {".": {"accounts": "Account", "sessions": "LoginSession"}}
        """
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - Account: accounts
          - LoginSession: sessions
        """

  Rule: PostgreSQL DDL 跨檔重複 table 應被拒絕
    Example: same table name in two PostgreSQL DDL files
      Given a temporary data directory
      And a schema file "a.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "b.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      When build_mapping plan is run against the data directory
      Then CLI exit code is 3
      And CLI stderr should contain "duplicate table 'accounts'"

  Rule: 含 0 個 table 的合法 PostgreSQL DDL 檔不報錯
    Example: PostgreSQL DDL file with no table definitions
      Given a temporary data directory
      And a schema file "empty.pg.sql" with content:
        """
        -- no tables here
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {}
        """
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping: []
        """
