Feature: unsupported schema dialects are explicitly ignored while their hand-converted mappings stay in the inventory

  Rule: 不支援副檔名的檔案不進命名 worklist，由 plan 以 ignored_files 顯式回報
    Example: a Cassandra .cql file is ignored while a .pg.sql file is planned
      Given a temporary data directory
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And a schema file "primary/events.cql" with content:
        """
        CREATE TABLE events (
          id uuid PRIMARY KEY
        );
        """
      When build_mapping plan is run against the data directory
      Then CLI exit code is 0
      And the plan for folder "primary" should list new tables ["accounts"]
      And the plan should list ignored files ["primary/events.cql"]

  Rule: 不含支援 schema 檔的資料夾之既有 mapping 視為 foreign mapping 納入盤點
    Example: a hand-converted mapping next to a .cql schema appears as a foreign mapping
      Given a temporary data directory
      And a schema file "cassandra/events.cql" with content:
        """
        CREATE TABLE events (
          id uuid PRIMARY KEY
        );
        """
      And an existing mapping "cassandra/entity_to_table_mapping.yml" with content:
        """
        entity_to_table_mapping:
          - AuditEvent: events
        """
      When build_mapping plan is run against the data directory
      Then CLI exit code is 0
      And the plan should include a foreign mapping at folder "cassandra" with entities [{"entity": "AuditEvent", "table": "events"}]
      And the plan should list no folder "cassandra"

  Rule: foreign mapping 自身內部若已有 entity name 撞名，也要被 apply 攔下而非靜默吃掉
    Example: the same entity name maps two different tables inside one foreign mapping
      Given a temporary data directory
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And an existing mapping "cassandra/entity_to_table_mapping.yml" with content:
        """
        entity_to_table_mapping:
          - AuditEvent: events
          - AuditEvent: sessions
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {"primary": {"accounts": "Account"}}
        """
      Then CLI exit code is 4
      And CLI stderr should contain "duplicate entity 'AuditEvent'"
      And CLI stderr should contain "foreign mapping"

  Rule: 新命名不得與 foreign mapping 已佔用的 entity name 撞名
    Example: naming a new table with an entity name a foreign mapping already claimed is rejected
      Given a temporary data directory
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And an existing mapping "cassandra/entity_to_table_mapping.yml" with content:
        """
        entity_to_table_mapping:
          - Account: events
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {"primary": {"accounts": "Account"}}
        """
      Then CLI exit code is 4
      And CLI stderr should contain "duplicate entity 'Account'"
      And CLI stderr should contain "foreign mapping"

  Rule: apply 嚴禁改寫 foreign mapping
    Example: applying names to a managed folder leaves the foreign mapping untouched
      Given a temporary data directory
      And a schema file "primary/account.pg.sql" with content:
        """
        CREATE TABLE public.accounts (
          id SERIAL PRIMARY KEY
        );
        """
      And an existing mapping "cassandra/entity_to_table_mapping.yml" with content:
        """
        entity_to_table_mapping:
          - AuditEvent: events
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {"primary": {"accounts": "Account"}}
        """
      Then CLI exit code is 0
      And the generated mapping at "primary/entity_to_table_mapping.yml" should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - Account: accounts
        """
      And the generated mapping at "cassandra/entity_to_table_mapping.yml" should equal:
        """
        entity_to_table_mapping:
          - AuditEvent: events
        """

  Rule: 整個 data 目錄只剩根層 foreign mapping 時不得被清空覆寫
    Example: a hand-converted root mapping with no supported schema files survives apply
      Given a temporary data directory
      And an existing mapping "entity_to_table_mapping.yml" with content:
        """
        entity_to_table_mapping:
          - AuditEvent: events
        """
      When build_mapping apply is run against the data directory with naming:
        """
        {}
        """
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        entity_to_table_mapping:
          - AuditEvent: events
        """
